# Generated by Django 4.0.4 on 2022-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=256, unique=True, verbose_name='Alias')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
    ]
